# Generated by Django 4.2.16 on 2024-11-06 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barRestaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='name',
            new_name='title',
        ),
    ]
