# Generated by Django 4.2.16 on 2024-11-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barRestaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
