# Generated by Django 4.2.16 on 2024-11-06 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('barRestaurant', '0002_rename_name_menuitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.TextField(),
        ),
    ]
